// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC04sRsf6nCHlhGYPTZly0b9dyS9_JTZE',
    appId: '1:184220087587:web:d858983383d82306b28896',
    messagingSenderId: '184220087587',
    projectId: 'todoexample-9c218',
    authDomain: 'todoexample-9c218.firebaseapp.com',
    storageBucket: 'todoexample-9c218.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHmKtnEn-ez3mrnVg9qFo7FYdET25PoMg',
    appId: '1:184220087587:android:8e338ba6df6d6f60b28896',
    messagingSenderId: '184220087587',
    projectId: 'todoexample-9c218',
    storageBucket: 'todoexample-9c218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2IVlZVOuLf7ed3Q29HHnsrYrvLLVzYDI',
    appId: '1:184220087587:ios:adc1567f49002fc1b28896',
    messagingSenderId: '184220087587',
    projectId: 'todoexample-9c218',
    storageBucket: 'todoexample-9c218.appspot.com',
    iosBundleId: 'com.example.todoExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2IVlZVOuLf7ed3Q29HHnsrYrvLLVzYDI',
    appId: '1:184220087587:ios:6b8f89338f94fca0b28896',
    messagingSenderId: '184220087587',
    projectId: 'todoexample-9c218',
    storageBucket: 'todoexample-9c218.appspot.com',
    iosBundleId: 'com.example.todoExample.RunnerTests',
  );
}
